### PR TITLE
Bot work from Nost TBC

### PR DESCRIPTION
**Pull request by Phatcat**
?

---

This change is [Reviewable](https://reviewable.io/reviews/blueboy/portalclassic/24)

### CODE REVIEW

**Comment by cala** [comment]
May be interesting. We are also thinking of adding playerbot in core, but this is stalled until the current heavy changes made core side (that includes your recent work) have calm down a bit. :)

**Comment by Phatcat** [comment]
No rest for the wicked, my good sir ;)

**Comment by Zooke** [comment]
I had numerous playability issues using bots that very sadly made me give up using them.
http://cmangos.net/thread-7465-post-46078.html#pid46078

**Comment by Phatcat** [comment]
@Zooke All the more reason to fix them, no? ;)

Those you speak of are AI issues. Maybe I should be taking a look at bots when I finally pull myself together to get started on the AI rework.

**Pull request closed without merging**
