### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yyhhrr**
I am Junior programmer with c++.And I did some ai improvement for fun, I test it by myself.Hope you guys can find something usefull.

### CODE REVIEW

**Comment by cala** [comment]
Thank you for this pull request. I saw there are many things into it. :+1: 
I'm leaving for holidays tonight, so I will review it when I come back in september.

A few kindly remarks/advices:
- I won't be able to merge the commits related to core fixes only. They should belong to the core repository, not playerbot repository where development is focused on bots only
- try to follow code styles (like using 4 white spaces instead of tabs for indentation), it makes diff far more easy to read and then to understand what you changed
- make complete commit names : it help other dev to understand your code more quickly
- it is sometimes better to have a few separate branches, each one focusing on a specific topic (mage branch, warrior branch, generic branch and so on): this makes pull request less clumsy

Overall, I saw many good things in your work, thank you. I'll take care of it when coming back from my holidays. :smile:

**Comment by yyhhrr** [comment]
Well,I love playerbot and cmangos ,I played wow with playerbot everyday mostly.
I will continue work on playerbot if i have enough time.

**Comment by cala** [comment]
Good to hear that. :+1:

**Comment by cala** [comment]
I'm back from holidays. I have a few things on database and scripts that I must do first, but I will definitely look at your work after. Thanks :-)

**Pull request closed without merging**
